// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
// import consumer from '../channels/consumer'

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)





// import StimulusReflex from 'stimulus_reflex'
// StimulusReflex.initialize(application, { consumer, controller, isolate: true })
// StimulusReflex.debug = process.env.RAILS_ENV === 'development'

