#https://crontab.guru/

check_orders:
  cron: "*/30 * * * *" # execute at every 30 minute
  class: "Wb::OrderCheckWorker"
  queue: 'check_orders'

check_sales:
  cron: "*/30 * * * *" # execute at every 30 minute
  class: "Wb::SalesCheckWorker"
  queue: 'check_sales'

parse_product_pages:
  cron: "*/30 * * * *" # execute at every 30 minute
  class: "Wb::ProductParserWorker"
  queue: 'parse_page'

check_stock:
  cron: "0 9,19 * * *" # execute at every 9amm, 19pm minute
  class: "Wb::StocksCheckWorker"
  queue: 'check_stocks'

parse_stores_page:
  cron: "0 * * * *" # execute at every hour
  class: "Wb::ParseStoresWorker"
  queue: 'parse_store_page'

#check_ads:
#  cron: "*/30 * * * *" # execute at every 30 minute
#  class: "Wb::AdCheckWorker"
#  queue: 'default'


#check_position:
#  cron: "0 7,18 * * *" # execute at every 30 minute
#  class: "Wb::PositionCheckWorker"
#  queue: 'default'

#order_notifications_tg:
#  cron: "*/1 * * * *" # execute at every 30 minute
#  class: "Wb::OrderNotificationsWorker"
#  queue: 'default'

#sales_notifications_tg:
#  cron: "*/1 * * * *" # execute at every 30 minute
#  class: "Wb::SalesNotificationsWorker"
#  queue: 'default'
