:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 3
staging:
  :concurrency: 2
development:
  :concurrency: 3
:queues:
  - [default, 3]
  - [check_sales, 3]
  - [check_orders, 3]
  - [check_stocks, 3]
  - [parse_page, 3]
